name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Publish JS Filename
        id: publish
        run: find/dist/assest/*.js -type f -execdir echo "script-file={}" >> $GITHUB_OUTPUT
      - name: Create Artifacts
        uses: actions/upload-artifact@v4   #uploads a zip file
        with:
          name: dist-files
          path: dist
#          path: |
#            dist
#            package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4  #downloads and extract the zip file
        with:
          name: dist-files
      - name: List file present in workflow folder
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."